name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - 'docs/**'
      - '.markdownlint.json'
      - '.github/workflows/docs.yaml'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '**.md'
      - 'docs/**'
      - '.markdownlint.json'
      - '.github/workflows/docs.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff # v24.2.0
        with:
          globs: '**/*.md'
